#!/bin/bash
# Audit Report Generator
# Purpose: Generate audit reports for review
# Usage: ./audit-report.sh [--day|--week|--month]

WORKSPACE="/Users/levinolonan/.openclaw/workspace"
AUDIT_LOG="$WORKSPACE/safety/audit/audit-log.jsonl"
REPORT_DIR="$WORKSPACE/safety/audit/reports"

# Ensure directories exist
mkdir -p "$REPORT_DIR"

# Generate daily report
generate_daily() {
    local date="${1:-$(date +%Y-%m-%d)}"
    local report_file="$REPORT_DIR/audit-daily-$date.md"
    
    echo "=== Generating Daily Audit Report: $date ==="
    
    local count=$(grep -c "\"timestamp\": \"$date" "$AUDIT_LOG" 2>/dev/null || echo "0")
    
    cat > "$report_file" << EOF
# Daily Audit Report

**Date:** $date  
**Generated:** $(date '+%Y-%m-%d %H:%M:%S')

## Summary

- Total entries: $count
- Report period: 24 hours

## Entries

EOF

    if [ "$count" -gt 0 ]; then
        grep "\"timestamp\": \"$date" "$AUDIT_LOG" | while read -r line; do
            local timestamp=$(echo "$line" | grep -o '"timestamp": "[^"]*"' | cut -d'"' -f4)
            local action=$(echo "$line" | grep -o '"action": "[^"]*"' | cut -d'"' -f4)
            local actor=$(echo "$line" | grep -o '"actor": "[^"]*"' | cut -d'"' -f4)
            local result=$(echo "$line" | grep -o '"result": "[^"]*"' | cut -d'"' -f4)
            
            echo "- [$timestamp] $actor: $action → $result" >> "$report_file"
        done
    else
        echo "No audit entries for this date." >> "$report_file"
    fi
    
    cat >> "$report_file" << EOF

## Statistics

### Actions
EOF

    # Action stats
    grep "\"timestamp\": \"$date" "$AUDIT_LOG" 2>/dev/null | cut -d'"' -f8 | sort | uniq -c | sort -rn | head -10 >> "$report_file" || echo "No data" >> "$report_file"
    
    echo "" >> "$report_file"
    echo "---" >> "$report_file"
    echo "" >> "$report_file"
    echo "*Report generated by audit system*" >> "$report_file"
    
    echo "Report saved: $report_file"
}

# Generate weekly report
generate_weekly() {
    local report_file="$REPORT_DIR/audit-weekly-$(date +%Y-W%U).md"
    
    echo "=== Generating Weekly Audit Report ==="
    
    local week_start=$(date -v-sun -v-6d +%Y-%m-%d 2>/dev/null || date -d "last sunday - 6 days" +%Y-%m-%d)
    local week_end=$(date +%Y-%m-%d)
    
    cat > "$report_file" << EOF
# Weekly Audit Report

**Week:** $(date +%U)  
**Period:** $week_start to $week_end  
**Generated:** $(date '+%Y-%m-%d %H:%M:%S')

## Summary

- Total entries: $(wc -l < "$AUDIT_LOG" 2>/dev/null || echo "0")
- Period: 7 days

## Daily Breakdown

| Date | Entries |
|------|---------|
EOF

    for i in 0 1 2 3 4 5 6; do
        local d=$(date -v-${i}d +%Y-%m-%d 2>/dev/null || date -d "$i days ago" +%Y-%m-%d)
        local c=$(grep -c "\"timestamp\": \"$d" "$AUDIT_LOG" 2>/dev/null || echo "0")
        echo "| $d | $c |" >> "$report_file"
    done
    
    cat >> "$report_file" << EOF

## Top Actions

EOF

    # Top actions for the week
    tail -n 1000 "$AUDIT_LOG" 2>/dev/null | cut -d'"' -f8 | sort | uniq -c | sort -rn | head -10 >> "$report_file" || echo "No data" >> "$report_file"
    
    cat >> "$report_file" << EOF

## Security Notes

- Review any failed actions
- Check for unusual patterns
- Verify authorized access

---

*Report generated by audit system*
EOF

    echo "Report saved: $report_file"
}

# Main
main() {
    case "${1:-}" in
        --day)
            generate_daily "${2:-$(date +%Y-%m-%d)}"
            ;;
        --week)
            generate_weekly
            ;;
        --month)
            echo "Monthly report not yet implemented"
            ;;
        *)
            echo "Audit Report Generator"
            echo ""
            echo "Usage:"
            echo "  $0 --day [YYYY-MM-DD]     Generate daily report"
            echo "  $0 --week                 Generate weekly report"
            echo "  $0 --month                Generate monthly report"
            ;;
    esac
}

main "$@"
